# Generated by Django 4.1.2 on 2022-10-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(max_length=200)),
                ('nama_mk', models.CharField(max_length=200)),
                ('nama_dosen', models.CharField(max_length=200)),
                ('wp', models.CharField(max_length=200)),
                ('sks', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
